import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import { ArrowRight, BriefcaseBusiness, CircleDashed, FileText, Flame, MessageSquare, Sparkles, Target, UploadCloud, type LucideIcon } from 'lucide-react';

interface Summary { total_applications: number; interviews_count: number; offers_count: number; interview_rate: number; }
interface Job { job_id: number; job_title: string; company_name: string; match_score: number; }
const focusItems: { icon: LucideIcon; label: string }[] = [
  { icon: FileText, label: 'Tune your resume' },
  { icon: Target, label: 'Review your top match' },
  { icon: CircleDashed, label: 'Follow up on an application' },
];
const Metric = ({ label, value, detail, color }: { label: string; value: string | number; detail: string; color: string }) => <div className="rounded-2xl border border-white/70 bg-white/85 p-5 shadow-[0_8px_30px_rgb(15,23,42,0.04)] dark:border-slate-800 dark:bg-slate-900/70"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{label}</span><span className={`h-2 w-2 rounded-full ${color}`} /></div><p className="mt-3 text-3xl font-black tracking-tight text-slate-900 dark:text-white">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div>;

const Dashboard: React.FC = () => {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(true);
  const [resumeMissing, setResumeMissing] = useState(false);
  useEffect(() => { (async () => { try { const [analytics, matches] = await Promise.all([api.get('/analytics'), api.get('/jobs/matched')]); setSummary(analytics.data.summary); setJobs(matches.data.slice(0, 3)); } catch (err: any) { if (err.response?.status === 400) setResumeMissing(true); } finally { setLoading(false); } })(); }, []);
  if (loading) return <div className="space-y-6"><div className="shimmer-surface h-36 rounded-3xl" /><div className="grid gap-5 md:grid-cols-3">{[1,2,3].map(i => <div key={i} className="shimmer-surface h-36 rounded-2xl" />)}</div><div className="shimmer-surface h-80 rounded-3xl" /></div>;
  return <div className="relative space-y-7 overflow-hidden pb-8">
    <div className="ambient-orb -top-20 right-0 h-72 w-72 bg-fuchsia-300/25 dark:bg-fuchsia-600/10" /><div className="ambient-orb top-72 -left-28 h-80 w-80 bg-indigo-300/20 dark:bg-indigo-500/10 [animation-delay:-4s]" />
    <section className="relative overflow-hidden rounded-3xl bg-[#15152a] px-6 py-8 text-white shadow-xl shadow-indigo-950/15 md:px-9"><div className="aurora-grid absolute inset-0 opacity-80" /><div className="absolute -right-8 -top-12 h-48 w-48 rounded-full bg-violet-500/30 blur-3xl animate-soft-pulse" /><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1 text-[11px] font-bold text-indigo-100"><Sparkles size={13} className="text-fuchsia-300" />YOUR CAREER COMMAND CENTER</div><h1 className="text-3xl font-black tracking-tight md:text-4xl">Make your next move<br /><span className="text-indigo-300">a smart one.</span></h1><p className="mt-3 max-w-md text-sm leading-relaxed text-slate-300">Your search is building momentum. Keep the small actions moving and the results follow.</p></div><Link to="/jobs" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-indigo-950 transition-transform hover:-translate-y-0.5">Explore opportunities <ArrowRight size={16} /></Link></div></section>
    <section className="relative grid gap-5 md:grid-cols-3"><Metric label="Active applications" value={summary?.total_applications ?? 0} detail="Keep your pipeline warm" color="bg-indigo-500" /><Metric label="Interview rate" value={`${summary?.interview_rate ?? 0}%`} detail={`${summary?.interviews_count ?? 0} conversations in motion`} color="bg-fuchsia-500" /><Metric label="Offers received" value={summary?.offers_count ?? 0} detail="Your wins belong here" color="bg-emerald-500" /></section>
    {resumeMissing && <div className="relative flex flex-col justify-between gap-4 rounded-2xl border border-amber-200/80 bg-amber-50/75 p-5 dark:border-amber-900/60 dark:bg-amber-950/15 sm:flex-row sm:items-center"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-600 dark:bg-amber-900/30"><UploadCloud size={18} /></div><div><p className="text-sm font-bold text-amber-950 dark:text-amber-300">Your search is waiting for its cheat code.</p><p className="mt-0.5 text-xs text-amber-800/70 dark:text-amber-400">Upload your resume to unlock tailored roles and ATS insights.</p></div></div><Link to="/resume" className="text-sm font-bold text-amber-700 hover:underline dark:text-amber-300">Upload resume →</Link></div>}
    <div className="relative grid gap-7 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-3xl border border-white bg-white/80 p-6 shadow-[0_8px_30px_rgb(15,23,42,0.04)] dark:border-slate-800 dark:bg-slate-900/70"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-500">Top picks</p><h2 className="mt-1 text-xl font-black tracking-tight text-slate-900 dark:text-white">Roles with real potential</h2></div><Link to="/jobs" className="text-xs font-bold text-indigo-600 hover:underline">View all</Link></div><div className="mt-5 space-y-3">{jobs.length ? jobs.map((job, i) => <div key={job.job_id} className="group flex items-center gap-3 rounded-2xl border border-slate-100 bg-white p-4 transition-all hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-black ${i === 0 ? 'bg-indigo-100 text-indigo-600' : i === 1 ? 'bg-fuchsia-100 text-fuchsia-600' : 'bg-emerald-100 text-emerald-600'}`}>{job.company_name.slice(0, 1)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900 dark:text-white">{job.job_title}</p><p className="mt-0.5 text-xs text-slate-500">{job.company_name}</p></div><div className="text-right"><div className="text-sm font-black text-indigo-600">{job.match_score}%</div><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">match</div></div></div>) : <div className="py-9 text-center"><BriefcaseBusiness className="mx-auto text-slate-300" size={28}/><p className="mt-2 text-sm text-slate-500">New opportunities will show up here.</p></div>}</div></section>
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-700 p-6 text-white shadow-xl shadow-indigo-500/20"><div className="absolute -right-10 bottom-0 h-44 w-44 rounded-full border-[24px] border-white/10" /><div className="relative"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white/15"><Flame size={19} /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-indigo-200">Today’s focus</p><h2 className="mt-1 text-xl font-black tracking-tight">Build a profile recruiters stop for.</h2><div className="mt-6 space-y-3">{focusItems.map(({ icon: TaskIcon, label }, i) => <div key={i} className="flex items-center gap-3 text-sm text-indigo-50"><span className="grid h-6 w-6 place-items-center rounded-full border border-white/25"><TaskIcon size={13} /></span>{label}</div>)}</div><Link to="/resume" className="mt-7 inline-flex items-center gap-2 text-sm font-bold hover:text-indigo-100">Start a power move <ArrowRight size={15}/></Link></div></section></div>
    <section className="relative rounded-3xl border border-white bg-white/80 p-6 dark:border-slate-800 dark:bg-slate-900/70"><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-fuchsia-100 text-fuchsia-600 dark:bg-fuchsia-500/15"><MessageSquare size={19}/></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-fuchsia-500">Career coach</p><h2 className="mt-1 text-base font-black text-slate-900 dark:text-white">“Your next best action: tailor your strongest project to your top role.”</h2><p className="mt-1 text-sm text-slate-500">Specific beats perfect. Make every application feel intentional.</p></div></div></section>
  </div>;
};
export default Dashboard;
