import React, { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { CheckCircle2, KeyRound } from 'lucide-react';
import api from '../services/api';

const ResetPassword: React.FC = () => {
  const [params] = useSearchParams(); const navigate = useNavigate();
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [done, setDone] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (password.length < 8) return setError('Use at least 8 characters.'); if (password !== confirm) return setError('Passwords do not match.'); const token = params.get('token'); if (!token) return setError('This reset link is invalid or incomplete.'); setLoading(true); try { await api.post('/auth/reset-password', { token, new_password: password }); setDone(true); setTimeout(() => navigate('/login'), 1400); } catch (err: any) { setError(err.response?.data?.detail || 'This reset link is invalid or has expired.'); } finally { setLoading(false); } };
  return <div className="min-h-screen grid place-items-center bg-slate-50 px-4 dark:bg-slate-950"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl dark:border-slate-800 dark:bg-slate-900">{done ? <div className="text-center"><CheckCircle2 className="mx-auto text-emerald-500" size={46}/><h1 className="mt-4 text-2xl font-black text-slate-900 dark:text-white">Password updated</h1><p className="mt-2 text-sm text-slate-500">Taking you back to sign in…</p></div> : <><div className="grid h-12 w-12 place-items-center rounded-2xl bg-indigo-100 text-indigo-600 dark:bg-indigo-500/15"><KeyRound size={22}/></div><h1 className="mt-5 text-2xl font-black text-slate-900 dark:text-white">Choose a new password</h1><form onSubmit={submit} className="mt-6 space-y-4">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<input required type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="New password (8+ characters)" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-indigo-500 dark:border-slate-700 dark:bg-slate-800 dark:text-white"/><input required type="password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="Confirm new password" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-indigo-500 dark:border-slate-700 dark:bg-slate-800 dark:text-white"/><button disabled={loading} className="w-full rounded-xl bg-indigo-600 py-3 text-sm font-bold text-white hover:bg-indigo-500 disabled:opacity-60">{loading ? 'Updating…' : 'Reset password'}</button></form><Link to="/login" className="mt-6 block text-center text-sm font-semibold text-slate-500 hover:text-indigo-600">Back to sign in</Link></>}</div></div>;
};
export default ResetPassword;
