from typing import Any, List
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_
from sqlalchemy.orm import selectinload
import uuid
import os

from app.database import get_db
from app.models.models import Job, Resume, CoverLetter, InterviewQuestion, User, Company
from app.schemas.schemas import (
    CoverLetterOut,
    InterviewQuestionOut,
    CoverLetterCreate,
)
from app.api.deps import get_current_active_user
from app.services.optimization_service import optimization_service
from app.core.config import settings

router = APIRouter(prefix="/optimization", tags=["optimization"])


@router.post("/resume")
async def optimize_user_resume(
    job_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Generate an ATS-optimized summary, skills, and projects for a specific job posting compared to user's resume.
    """
    # Fetch active resume
    res_query = select(Resume).where(Resume.user_id == current_user.id).order_by(Resume.created_at.desc())
    res_exec = await db.execute(res_query)
    resume = res_exec.scalar_one_or_none()
    
    if not resume:
        raise HTTPException(
            status_code=400,
            detail="No uploaded resume found. Please upload a PDF/DOCX resume first."
        )
        
    # Fetch target job
    job_query = select(Job).where(Job.id == job_id)
    job_exec = await db.execute(job_query)
    job = job_exec.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job posting not found.")
        
    optimization = await optimization_service.optimize_resume(
        resume.raw_text or "", job.title, job.description
    )
    return optimization


@router.post("/cover-letter", response_model=CoverLetterOut)
async def generate_user_cover_letter(
    job_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Generate a personalized cover letter matching the user's resume and a specific job posting.
    Saves it to the database for subsequent edits/downloads.
    """
    res_query = select(Resume).where(Resume.user_id == current_user.id).order_by(Resume.created_at.desc())
    res_exec = await db.execute(res_query)
    resume = res_exec.scalar_one_or_none()
    
    if not resume:
        raise HTTPException(
            status_code=400,
            detail="No uploaded resume found. Please upload a PDF/DOCX resume first."
        )
        
    job_query = select(Job).where(Job.id == job_id)
    job_exec = await db.execute(job_query)
    job = job_exec.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job posting not found.")
        
    # Get company name
    comp_query = select(Company).where(Company.id == job.company_id)
    comp_exec = await db.execute(comp_query)
    company = comp_exec.scalar_one_or_none()
    company_name = company.name if company else "Target Company"
    
    # Generate cover letter text
    letter_text = await optimization_service.generate_cover_letter(
        resume.raw_text or "", job.title, company_name, job.description
    )
    
    # Save or update cover letter
    cl_query = select(CoverLetter).where(
        and_(CoverLetter.user_id == current_user.id, CoverLetter.job_id == job_id)
    )
    cl_exec = await db.execute(cl_query)
    cl = cl_exec.scalar_one_or_none()
    
    if cl:
        cl.content = letter_text
    else:
        cl = CoverLetter(user_id=current_user.id, job_id=job_id, content=letter_text)
        db.add(cl)
        
    await db.commit()
    await db.refresh(cl)
    
    # Reload with full relations
    stmt = select(CoverLetter).options(selectinload(CoverLetter.job).selectinload(Job.company)).where(CoverLetter.id == cl.id)
    res = await db.execute(stmt)
    return res.scalar_one()


@router.get("/cover-letters", response_model=List[CoverLetterOut])
async def read_cover_letters(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Get all cover letters generated by the user.
    """
    query = select(CoverLetter).where(CoverLetter.user_id == current_user.id).order_by(CoverLetter.updated_at.desc())
    result = await db.execute(query)
    return result.scalars().all()


@router.get("/cover-letters/{cl_id}", response_model=CoverLetterOut)
async def read_cover_letter(
    cl_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Get detailed content of a specific cover letter.
    """
    query = select(CoverLetter).where(
        and_(CoverLetter.id == cl_id, CoverLetter.user_id == current_user.id)
    )
    result = await db.execute(query)
    cl = result.scalar_one_or_none()
    if not cl:
        raise HTTPException(status_code=404, detail="Cover letter not found.")
    return cl


@router.put("/cover-letters/{cl_id}", response_model=CoverLetterOut)
async def update_cover_letter(
    cl_id: int,
    content: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Save custom edits to a cover letter.
    """
    query = select(CoverLetter).where(
        and_(CoverLetter.id == cl_id, CoverLetter.user_id == current_user.id)
    )
    result = await db.execute(query)
    cl = result.scalar_one_or_none()
    if not cl:
        raise HTTPException(status_code=404, detail="Cover letter not found.")
        
    cl.content = content
    db.add(cl)
    await db.commit()
    await db.refresh(cl)
    return cl


@router.get("/cover-letters/{cl_id}/download/{file_format}")
async def download_cover_letter(
    cl_id: int,
    file_format: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Compile and download cover letter as PDF or DOCX file format.
    """
    if file_format.lower() not in ["pdf", "docx"]:
        raise HTTPException(status_code=400, detail="Invalid format. Supported: pdf, docx")
        
    query = select(CoverLetter).where(
        and_(CoverLetter.id == cl_id, CoverLetter.user_id == current_user.id)
    )
    result = await db.execute(query)
    cl = result.scalar_one_or_none()
    if not cl:
        raise HTTPException(status_code=404, detail="Cover letter not found.")
        
    # Setup temporary download directories
    temp_dir = os.path.join(settings.UPLOAD_DIR, "downloads")
    os.makedirs(temp_dir, exist_ok=True)
    
    unique_name = f"cover_letter_{cl_id}_{uuid.uuid4()}"
    
    if file_format.lower() == "pdf":
        file_path = os.path.join(temp_dir, f"{unique_name}.pdf")
        optimization_service.export_pdf(cl.content, file_path)
        media_type = "application/pdf"
    else:
        file_path = os.path.join(temp_dir, f"{unique_name}.docx")
        optimization_service.export_docx(cl.content, file_path)
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        
    return FileResponse(
        path=file_path,
        media_type=media_type,
        filename=f"Cover_Letter_{cl_id}.{file_format.lower()}"
    )


@router.post("/interview-prep", response_model=List[InterviewQuestionOut])
async def generate_interview_prep(
    job_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Generate tailored interview prep questions (technical, behavioral, etc.) based on a job description.
    Saves questions in user portfolio.
    """
    job_query = select(Job).where(Job.id == job_id)
    job_exec = await db.execute(job_query)
    job = job_exec.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job posting not found.")
        
    # Get company name
    comp_query = select(Company).where(Company.id == job.company_id)
    comp_exec = await db.execute(comp_query)
    company = comp_exec.scalar_one_or_none()
    company_name = company.name if company else "Target Company"
    
    questions = await optimization_service.generate_interview_questions(
        job.title, company_name, job.description
    )
    
    saved_records = []
    for q in questions:
        # Avoid duplicates for same user/job/question text
        dupe_chk = await db.execute(
            select(InterviewQuestion).where(
                and_(
                    InterviewQuestion.user_id == current_user.id,
                    InterviewQuestion.job_id == job_id,
                    InterviewQuestion.question == q["question"]
                )
            )
        )
        existing = dupe_chk.scalar_one_or_none()
        if existing:
            saved_records.append(existing)
            continue
            
        record = InterviewQuestion(
            user_id=current_user.id,
            job_id=job_id,
            question_type=q["question_type"],
            question=q["question"],
            expected_answer=q["expected_answer"],
            difficulty=q["difficulty"]
        )
        db.add(record)
        saved_records.append(record)
        
    await db.commit()
    
    # Return details
    result = await db.execute(
        select(InterviewQuestion).where(
            and_(InterviewQuestion.user_id == current_user.id, InterviewQuestion.job_id == job_id)
        )
    )
    return result.scalars().all()


@router.get("/interview-questions", response_model=List[InterviewQuestionOut])
async def read_interview_questions(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
) -> Any:
    """
    Get all interview questions saved in user portfolio.
    """
    query = select(InterviewQuestion).where(InterviewQuestion.user_id == current_user.id).order_by(InterviewQuestion.created_at.desc())
    result = await db.execute(query)
    return result.scalars().all()
